### ISSUE TITLE
Bug: Cannot set property isTrusted of #<Event> [canary]

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-test-helpers#1077]
On latest canary, I get the error:

```
 TypeError: Cannot set property isTrusted of #<Event> which has only a getter
                at Function.assign (<anonymous>)
                at assign (http://localhost:7357/assets/vendor.js:38987:19)
                at buildBasicEvent (http://localhost:7357/assets/test-support.js:4449:27)
                at fireEvent (http://localhost:7357/assets/test-support.js:4429:15)
                at http://localhost:7357/assets/test-support.js:4271:30
```

When running tests.

I would suspect this is because on latest canary `assign` from` @ember/polyfills` just re-exports `Object.assign` and this implementation somehow breaks here:

https://github.com/emberjs/ember-test-helpers/blob/e55740d848f98530fa3ddb6faf655285d66cfa58/addon-test-support/%40ember/test-helpers/dom/fire-event.ts#L137

 I will look into it to see if I can find the issue.

**Comment by mydea** [comment]
Ok, this is actually a bug in ember, I opened a PR with a fix here: https://github.com/emberjs/ember.js/pull/19692
