### ISSUE TITLE
beta/canary failure

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember-test-helpers#1112]
```js
Build Error (PackagerRunner) in ../../../../node_modules/@ember/test-helpers/setup-rendering-context.js

Module build failed (from ../../../../../../../../../../../../Users/spenner/src/embroider-build/embroider/packages/babel-loader-8/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) TypeError: $TMPDIR/embroider/cb03bb/node_modules/@ember/test-helpers/setup-rendering-context.js/setup-rendering-context.js: Cannot read property 'visitor' of undefined
    at processResult (/Users/spenner/src/embroider-build/embroider/node_modules/webpack/lib/NormalModule.js:718:12)
    at /Users/spenner/src/embroider-build/embroider/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/spenner/src/embroider-build/embroider/node_modules/babel-loader/lib/index.js:59:103
```

I am currently debugging

**Comment by stefanpenner** [comment]
The issue isn't related to this at all, rather what appears to be a very broken error message from webpack...

It appears the issue is here: https://github.com/emberjs/ember.js/issues/19724
