### ISSUE TITLE
Can't build docs

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-test-helpers#1241]
I noticed the docs for `tab` were missing, so I tried to submit a PR, noticing that the docs were generated, and when I ran the generation command, I get an error: 
```
❯ yarn docs
yarn run v1.22.4
$ documentation build --document-exported "addon-test-support/@ember/test-helpers/index.js" --config documentation.yml --markdown-toc-max-depth 3 -f md -o API.md
Error: Unable to find the value DeprecationFailure in <repo>/addon-test-support/@ember/test-helpers/setup-context.js
    at <repo>/node_modules/documentation/src/extractors/exported.js:128:19
    at Array.forEach (<anonymous>)
    at ExportDeclaration (<repo>/node_modules/documentation/src/extractors/exported.js:97:20)
    at NodePath._call (<repo>/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (<repo>/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (<repo>/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (<repo>/node_modules/@babel/traverse/lib/context.js:99:16)
    at TraversalContext.visitMultiple (<repo>/node_modules/@babel/traverse/lib/context.js:68:17)
    at TraversalContext.visit (<repo>/node_modules/@babel/traverse/lib/context.js:125:19)
    at Function.traverse.node (<repo>/node_modules/@babel/traverse/lib/index.js:76:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.}
```

**Comment by chriskrycho** [comment]
Don't know what the issue was back in July, but this is working fine now (I did it a few times today!) so closing. Thanks!
