### ISSUE TITLE
Error: waitUntil timed out

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-test-helpers#321]
Since updating, I am experiencing weird errors in my tests.

For example, I have a test like this:

```js
test('selecting a lab works', async function(assert) {
  assert.expect(1);

  this.on('update', function(options) {
    assert.ok(true, 'the update action is called');
  });

  this.render(hbs`{{my-component update=(action 'update')}}`);

  await selectChoose('[data-test-my-select]', 'Lab 3'););
});
```

Which now gives me the following error:

```js
Uncaught Error: waitUntil timed out
    at waitUntil (http://localhost:4200/assets/test-support.js:10757:29)
    at wait (http://localhost:4200/assets/test-support.js:15122:39)
    at focus (http://localhost:4200/assets/test-support.js:11946:42)
    at clickEventSequence (http://localhost:4200/assets/test-support.js:11488:22)
    at click (http://localhost:4200/assets/test-support.js:11513:5)
    at _callee$ (http://localhost:4200/assets/test-support.js:12802:55)
    at tryCatch (http://localhost:4200/assets/vendor.js:6905:40)
    at Generator.invoke [as _invoke] (http://localhost:4200/assets/vendor.js:7143:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4200/assets/vendor.js:6957:21)
    at step (http://localhost:4200/assets/test-support.js:12611:32)
```

With the following stack:

```js
  | waitUntil | @ | wait-until.js:31
  | wait | @ | wait.js:59
  | focus | @ | focus.js:48
  | clickEventSequence | @ | click.js:19
  | click | @ | click.js:44
  | _callee$ | @ | helpers.js:419
  | tryCatch | @ | polyfill.js:6900
  | invoke | @ | polyfill.js:7138
  | prototype.(anonymous function) | @ | polyfill.js:6952
  | step | @ | helpers.js:228
  | (anonymous) | @ | helpers.js:239
  | setTimeout (async) |   |  
  | Backburner.platform.next | @ | backburner.js:412
  | _ensureInstance | @ | backburner.js:917
  | schedule | @ | backburner.js:547
  | (anonymous) | @ | rsvp.js:24
  | reject | @ | rsvp.js:340
  | (anonymous) | @ | rsvp.js:429
  | (anonymous) | @ | wait-until.js:58
  | setTimeout (async) |   |  
  | scheduleCheck | @ | wait-until.js:43
  /...
```

I am not quite sure if that belongs here or to ember-power-select. But I also seemed to get that error sometimes in my tests when simply using:

```js
import wait from 'ember-test-helpers/wait';

// ...
await wait();
// ...

**Comment by Turbo87** [comment]
have a look at https://github.com/emberjs/ember-test-helpers/issues/318. this should be fixed with the latest release of `@ember/test-helpers` so make sure your dependencies are up-to-date.

**Comment by mydea** [comment]
As far as I see, 0.7.18 is not actually released on npm yet? Or at least, I cannot seem to find it. 0.7.17 is the latest for me!

**Comment by Turbo87** [comment]
ouch, good point. see https://github.com/emberjs/ember-test-helpers/issues/322
