### ISSUE TITLE
Is Ember 1.12 supported with the new API?

### ISSUE THREAD

**Issue by andreyfel** [emberjs/ember-test-helpers#355]
I'm trying to get new API working with Ember 1.12.2 app. I've set up tests as it is shown in documentation. I'm getting the following error: 
`TypeError: Cannot read property 'buildInstance' of undefined
    at http://localhost:7357/assets/test-support.js:8525:20
    at tryCatch (http://localhost:7357/assets/vendor.js:55032:16)
    at invokeCallback (http://localhost:7357/assets/vendor.js:55044:17)
    at http://localhost:7357/assets/vendor.js:56943:13
    at http://localhost:7357/assets/vendor.js:36033:7
    at invoke (http://localhost:7357/assets/vendor.js:10428:18)
    at Queue.flush (http://localhost:7357/assets/vendor.js:10493:13)
    at DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:10298:19)
    at Backburner.end (http://localhost:7357/assets/vendor.js:9723:27)
    at http://localhost:7357/assets/vendor.js:10126:20`

**Comment by Turbo87** [comment]
nope, the minimum supported Ember version for the new testing APIs is 2.4.x

**Comment by andreyfel** [comment]
How does it work with ember-try If I use new testing API and specify 1.12 as one of the targets?

**Comment by Turbo87** [comment]
unfortunately you can't. we discovered similar issues for https://github.com/simplabs/ember-test-selectors, but other than dropping support for those older Ember versions there is not much we can do about it.
